"""Generate mc-polygon-table.js from tri table in mc-tables.js. Run from src/tables/unused/mc-polygon."""
import json
import os

# Paths relative to this script (unused/mc-polygon/) -> tables/ is ../..
script_dir = os.path.dirname(os.path.abspath(__file__))
tables_dir = os.path.join(script_dir, "..", "..")
mc_tables_path = os.path.join(tables_dir, "mc-tables.js")
out_path = os.path.join(tables_dir, "mc-polygon-table.js")

with open(mc_tables_path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.find("export const triTable = [")
if start < 0:
    raise SystemExit("triTable not found")
start = content.index("[", start)
depth = 1
i = start + 1
end = start + 1
while depth and i < len(content):
    if content[i] == "[":
        depth += 1
    elif content[i] == "]":
        depth -= 1
    end = i + 1
    i += 1
arr_str = content[start:end]
tri_table = json.loads(arr_str)

MC_POLY_ROW_SIZE = 17

def build_row(row):
    out = [-1] * MC_POLY_ROW_SIZE
    i, n_comp, k = 0, 0, 1
    while i + 2 < len(row) and row[i] != -1 and k < MC_POLY_ROW_SIZE - 2:
        a, b, c = row[i], row[i + 1], row[i + 2]
        i += 3
        if a == -1 or b == -1 or c == -1:
            break
        n_comp += 1
        out[k], out[k + 1], out[k + 2], out[k + 3] = 3, a, b, c
        k += 4
    out[0] = n_comp
    return out

table = [build_row(tri_table[case_idx]) for case_idx in range(256)]

out = """/**
 * MC extended polygon table (precomputed).
 * Row format: [n_components, nv_0, edge_idx..., nv_1, ...], -1 padded to 17.
 * Generated by gen_mc_polygon.py or build-mc-polygon-table.mjs — do not edit by hand.
 */
export const polygonTable = """ + json.dumps(table) + """;
"""
with open(out_path, "w", encoding="utf-8") as f:
    f.write(out)
print("Wrote", out_path)
